name: core-scripts-testing
run-name: ${{ github.head_ref || github.ref_name }}-core-scripts-testing

on:
  push:
  workflow_dispatch:


concurrency:
  group: core-scripts-testing${{ github.event.number }}
  cancel-in-progress: true


jobs:
  unit-test:
    name: "core-scripts-testing"
    runs-on: 'ubuntu-22.04'
    timeout-minutes: 20 # The overall timeout
    permissions: write-all

    steps:
      # checkout your repository
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Try to grant execution permission to test runner
        run: git update-index --chmod=+x ./addons/gdUnit4/runtest.sh
      # run tests by using the gdUnit4-action with Godot version 4.2.2 and the latest GdUnit4 release 
      - uses: MikeSchulze/gdUnit4-action@v1.1.1
        with:
          godot-version: '4.2.2'
          version: 'installed'
          godot-net: false
          godot-force-mono: true
          paths: 'res://TestsSource/Scripts/'
          timeout: 20
          report-name: test_report.xml
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Test Succeeded on ${{ github.head_ref || github.ref_name }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Test Failed on ${{ github.head_ref || github.ref_name }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}